services:
  db:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=grit
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=default
    image: "grit42com/pgrdkit:16.3-2024.03.1"
    platform: linux/amd64
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  app:
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=grit
      - POSTGRES_PASSWORD=password
      - GRIT_DATABASE=grit
      - SECRET_KEY_BASE=secretkeybase
    image: "grit42com/grit:0.1.1"
    platform: linux/amd64
    restart: unless-stopped
