packages:
    - "apps/grit/client"
    - "modules/**/frontend"
    - "modules/**/frontend/test/dummy"
    - "packages/frontend/*"

catalog:
    "@eslint/js": "9"
    "@tanstack/react-form": "0.42.1"
    "@tanstack/react-table": "8"
    "@tanstack/react-query": "5"
    "@tanstack/react-query-devtools": "5"
    "@tanstack/table-core": "8"
    "@types/node": "22"
    "@types/react": "18"
    "@types/react-dom": "18"
    "@vitejs/plugin-react": "4"
    autoprefixer: "10"
    axios: "1"
    eslint: "9"
    eslint-plugin-react-hooks: "5"
    eslint-plugin-react-refresh: "0.4"
    globals: "15"
    postcss: "8"
    prettier: "3"
    react: "18"
    react-dom: "18"
    react-helmet-async: "2"
    react-router-dom: "6"
    react-toastify: "11"
    sass-embedded: "1"
    typescript: "5.6"
    typescript-eslint: "8"
    vite: "5"
