export const TEST_ENTITY_COLUMNS = [
  {
    name: "id",
    display_name: "Id",
    description: null,
    type: "integer",
    limit: 8,
    required: true,
    unique: false,
    default_hidden: true,
  },
  {
    name: "created_by",
    display_name: "Created by",
    description: null,
    type: "string",
    limit: 30,
    required: true,
    unique: false,
    default_hidden: true,
  },
  {
    name: "created_at",
    display_name: "Created at",
    description: null,
    type: "datetime",
    limit: null,
    required: true,
    unique: false,
    default_hidden: true,
  },
  {
    name: "updated_by",
    display_name: "Updated by",
    description: null,
    type: "string",
    limit: 30,
    required: false,
    unique: false,
    default_hidden: true,
  },
  {
    name: "updated_at",
    display_name: "Updated at",
    description: null,
    type: "datetime",
    limit: null,
    required: false,
    unique: false,
    default_hidden: true,
  },
  {
    name: "name",
    display_name: "Name",
    description: null,
    type: "string",
    limit: null,
    required: true,
    unique: false,
    default_hidden: false,
  },
  {
    name: "another_string",
    display_name: "Another string",
    description: null,
    type: "string",
    limit: null,
    required: false,
    unique: false,
    default_hidden: false,
  },
  {
    name: "integer",
    display_name: "Integer",
    description: null,
    type: "integer",
    limit: 4,
    required: false,
    unique: false,
    default_hidden: false,
  },
  {
    name: "decimal",
    display_name: "Decimal",
    description: null,
    type: "decimal",
    limit: null,
    required: false,
    unique: false,
    default_hidden: false,
  },
  {
    name: "text",
    display_name: "Text",
    description: null,
    type: "text",
    limit: null,
    required: false,
    unique: false,
    default_hidden: false,
  },
  {
    name: "datetime",
    display_name: "Datetime",
    description: null,
    type: "datetime",
    limit: null,
    required: false,
    unique: false,
    default_hidden: false,
  },
  {
    name: "date",
    display_name: "Date",
    description: null,
    type: "date",
    limit: null,
    required: false,
    unique: false,
    default_hidden: false,
  },
  {
    name: "boolean",
    display_name: "Boolean",
    description: null,
    type: "boolean",
    limit: null,
    required: false,
    unique: false,
    default_hidden: false,
  },
  {
    name: "user_id__name",
    display_name: "User Name",
    description: null,
    type: "entity",
    limit: 8,
    required: false,
    unique: false,
    entity: {
      full_name: "Grit::Core::User",
      name: "User",
      path: "grit/core/users",
      primary_key: "id",
      primary_key_type: "integer",
      column: "user_id",
      display_column: "name",
      display_column_type: "string",
    },
    default_hidden: false,
  },
  {
    name: "user_id__login",
    display_name: "User Login",
    description: null,
    type: "entity",
    limit: 8,
    required: false,
    unique: false,
    entity: {
      full_name: "Grit::Core::User",
      name: "User",
      path: "grit/core/users",
      primary_key: "id",
      primary_key_type: "integer",
      column: "user_id",
      display_column: "login",
      display_column_type: "string",
    },
    default_hidden: false,
  },
];

export const TEST_ENTITY_FIELDS = [
  {
    name: "name",
    display_name: "Name",
    description: null,
    type: "string",
    limit: null,
    required: true,
    unique: true,
  },
  {
    name: "another_string",
    display_name: "Another string",
    description: null,
    type: "string",
    limit: null,
    required: false,
    unique: false,
  },
  {
    name: "integer",
    display_name: "Integer",
    description: null,
    type: "integer",
    limit: 4,
    required: false,
    unique: false,
  },
  {
    name: "decimal",
    display_name: "Decimal",
    description: null,
    type: "decimal",
    limit: null,
    required: false,
    unique: false,
  },
  {
    name: "text",
    display_name: "Text",
    description: null,
    type: "text",
    limit: null,
    required: false,
    unique: false,
  },
  {
    name: "datetime",
    display_name: "Datetime",
    description: null,
    type: "datetime",
    limit: null,
    required: false,
    unique: false,
  },
  {
    name: "date",
    display_name: "Date",
    description: null,
    type: "date",
    limit: null,
    required: false,
    unique: false,
  },
  {
    name: "boolean",
    display_name: "Boolean",
    description: null,
    type: "boolean",
    limit: null,
    required: false,
    unique: false,
  },
  {
    name: "user_id",
    display_name: "User",
    description: null,
    type: "entity",
    limit: 8,
    required: false,
    unique: false,
    entity: {
      full_name: "Grit::Core::User",
      name: "User",
      path: "grit/core/users",
      primary_key: "id",
      primary_key_type: "integer",
      column: "user_id",
      display_column: "name",
      display_column_type: "string",
    },
  },
];
