import { Surface } from "@grit42/client-library/components";
import { Sheet } from "@grit42/spreadsheet";
import { useMemo } from "react";
import { FormField, FormFieldDef, ReactFormExtendedApi } from "@grit42/form";

const SHEET_OPTIONS_FORM_FIELDS: FormFieldDef[] = [
  {
    name: "include",
    display_name: "Include this sheet",
    type: "boolean",
  },
  {
    name: "columnDefinitionsFromSheetOptions.nameRowIndex",
    display_name: "Index of the row containing the column name",
    description: "name will be autogenerated if not specified",
    type: "integer",
  },
  {
    name: "columnDefinitionsFromSheetOptions.descriptionRowIndex",
    display_name: "Index of the row containing the column description",
    type: "integer",
  },
  {
    name: "columnDefinitionsFromSheetOptions.identifierRowIndex",
    display_name: "Index of the row containing the column safe_name",
    description: "safe_name will be autogenerated if not specified",
    type: "integer",
  },
  {
    name: "columnDefinitionsFromSheetOptions.dataRowOffset",
    display_name: "Index of the first row containing data",
    type: "number",
  },
  {
    name: "columnDefinitionsFromSheetOptions.columnOffset",
    display_name: "Index of the first column containing data",
    type: "string",
  },
];

const SheetOptions = ({
  form,
  sheetIndex,
}: {
  form: ReactFormExtendedApi<any>;
  sheetIndex: number;
  sheet: Sheet;
}) => {
  const fields = useMemo(
    () =>
      SHEET_OPTIONS_FORM_FIELDS.map((f) => ({
        ...f,
        name: `sheets[${sheetIndex}].${f.name}`,
      })),
    [sheetIndex],
  );

  return (
    <Surface>
      <div
        style={{
          display: "grid",
          gridTemplateColumns: "1fr",
          gridAutoRows: "max-content",
          gap: "calc(var(--spacing) * 2)",
          paddingBottom: "calc(var(--spacing) * 2)",
        }}
      >
        {fields.map((f) => (
          <FormField form={form} fieldDef={f} key={f.name} />
        ))}
      </div>
    </Surface>
  );
};

export default SheetOptions;
