import { Surface } from "@grit42/client-library/components";
import { Sheet } from "@grit42/spreadsheet";
import { ReactFormExtendedApi, useFormInput, useStore } from "@grit42/form";

const SheetOptions = ({
  form,
  sheetIndex,
}: {
  form: ReactFormExtendedApi<any>;
  sheetIndex: number;
  sheet: Sheet;
}) => {
  const BooleanInput = useFormInput("boolean");
  const NumberInput = useFormInput("number");
  const StringInput = useFormInput("string");

  const included = useStore(
    form.baseStore,
    ({ values }) => values.sheets[sheetIndex].include,
  );

  return (
    <Surface style={{ overflowY: "auto" }}>
      <div
        style={{
          display: "grid",
          gridTemplateColumns: "1fr",
          gridAutoRows: "max-content",
          gap: "calc(var(--spacing) * 2)",
          paddingBottom: "calc(var(--spacing) * 2)",
          maxWidth: 400,
        }}
      >
        <p>
          Click a cell in the grid to use its row or column for one of the
          parameters
        </p>

        <form.Field name={`sheets[${sheetIndex}].include`}>
          {(field) => (
            <BooleanInput
              disabled={false}
              error=""
              field={{
                name: `sheets[${sheetIndex}].include`,
                display_name: "Include this sheet",
                required: true,
                type: "boolean",
              }}
              handleChange={field.handleChange}
              handleBlur={field.handleBlur}
              value={field.state.value}
            />
          )}
        </form.Field>
        <form.Field
          name={`sheets[${sheetIndex}].columnDefinitionsFromSheetOptions.nameRowIndex`}
          validators={{
            onChangeListenTo: [`sheets[${sheetIndex}].include`],
            onChange: ({ value, fieldApi }) => {
              if (!fieldApi.form.getFieldValue(`sheets[${sheetIndex}].include`))
                return undefined;
              else if (value === null || value === undefined || value === "") {
                return `cannot be blank`;
              }
            },
          }}
        >
          {(field) => (
            <NumberInput
              disabled={!included}
              error={Array.from(new Set(field.state.meta.errors)).join("\n")}
              field={{
                name: `sheets[${sheetIndex}].columnDefinitionsFromSheetOptions.nameRowIndex`,
                display_name: "Index of the row containing the column name",
                description: "name will be autogenerated if not specified",
                required: included,
                type: "integer",
              }}
              handleChange={field.handleChange}
              handleBlur={field.handleBlur}
              value={field.state.value}
            />
          )}
        </form.Field>
        <form.Field
          name={`sheets[${sheetIndex}].columnDefinitionsFromSheetOptions.dataRowOffset`}
          validators={{
            onChangeListenTo: [`sheets[${sheetIndex}].include`],
            onChange: ({ value, fieldApi }) => {
              if (!fieldApi.form.getFieldValue(`sheets[${sheetIndex}].include`))
                return undefined;
              else if (value === null || value === undefined || value === "") {
                return `cannot be blank`;
              }
            },
          }}
        >
          {(field) => (
            <NumberInput
              disabled={!included}
              error={Array.from(new Set(field.state.meta.errors)).join("\n")}
              field={{
                name: `sheets[${sheetIndex}].columnDefinitionsFromSheetOptions.dataRowOffset`,
                display_name: "Index of the first row containing data",
                required: included,
                type: "integer",
              }}
              handleChange={field.handleChange}
              handleBlur={field.handleBlur}
              value={field.state.value}
            />
          )}
        </form.Field>
        <form.Field
          name={`sheets[${sheetIndex}].columnDefinitionsFromSheetOptions.columnOffset`}
          validators={{
            onChangeListenTo: [`sheets[${sheetIndex}].include`],
            onChange: ({ value, fieldApi }) => {
              if (!fieldApi.form.getFieldValue(`sheets[${sheetIndex}].include`))
                return undefined;
              else if (value === null || value === undefined || value === "") {
                return `cannot be blank`;
              }
            },
          }}
        >
          {(field) => (
            <StringInput
              disabled={!included}
              error={Array.from(new Set(field.state.meta.errors)).join("\n")}
              field={{
                name: `sheets[${sheetIndex}].columnDefinitionsFromSheetOptions.columnOffset`,
                display_name: "Index of the first column containing data",
                required: included,
                type: "string",
              }}
              handleChange={field.handleChange}
              handleBlur={field.handleBlur}
              value={field.state.value}
            />
          )}
        </form.Field>
        <form.Field
          name={`sheets[${sheetIndex}].columnDefinitionsFromSheetOptions.descriptionRowIndex`}
        >
          {(field) => (
            <NumberInput
              disabled={!included}
              error={Array.from(new Set(field.state.meta.errors)).join("\n")}
              field={{
                name: `sheets[${sheetIndex}].columnDefinitionsFromSheetOptions.descriptionRowIndex`,
                display_name:
                  "Index of the row containing the column description",
                type: "integer",
              }}
              handleChange={field.handleChange}
              handleBlur={field.handleBlur}
              value={field.state.value}
            />
          )}
        </form.Field>
        <form.Field
          name={`sheets[${sheetIndex}].columnDefinitionsFromSheetOptions.identifierRowIndex`}
        >
          {(field) => (
            <NumberInput
              disabled={!included}
              error={Array.from(new Set(field.state.meta.errors)).join("\n")}
              field={{
                name: `sheets[${sheetIndex}].columnDefinitionsFromSheetOptions.identifierRowIndex`,
                display_name:
                  "Index of the row containing the column safe_name",
                description: "safe_name will be autogenerated if not specified",
                type: "integer",
              }}
              handleChange={field.handleChange}
              handleBlur={field.handleBlur}
              value={field.state.value}
            />
          )}
        </form.Field>
      </div>
    </Surface>
  );
};

export default SheetOptions;
