services:
  docs:
    build: .
    volumes:
      - './docs:/app/docs'
      - './src:/app/src'
      - './static:/app/static'
      - './docusaurus.config.ts:/app/docusaurus.config.ts'
      - './sidebars.ts:/app/sidebars.ts'
    ports:
      - "4242:4242"
    restart: unless-stopped
