source "https://rubygems.org"

# Specify your gem's dependencies in grit-compounds.gemspec.
gemspec

gem "puma"

gem "pg"

# Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
gem "rubocop-rails-omakase", require: false


gem "authlogic", github: "binarylogic/authlogic", branch: "master"

gem "grit-core", path: "../../core/backend"
