# frozen_string_literal: true

Rswag::Api.configure do |c|
  # Specify the root folder where OpenAPI/Swagger JSON files are located.
  # These are generated by rswag:specs:swaggerize in each engine module
  # and aggregated here via rake task.
  c.openapi_root = Rails.root.join("openapi").to_s
end
