import { useCreateEntityMutation, useEntityData } from "@grit42/core";
import {
  Button,
  ButtonGroup,
  ErrorPage,
  Spinner,
  Surface,
  Tabs,
} from "@grit42/client-library/components";
import { Navigate, useNavigate } from "react-router-dom";
import { useQuery } from "@grit42/api";
import {
  sampleSheetData,
  sheetDefinitionsFromFiles,
  Sheet,
  utils,
  ColumnDefinitionsFromSheetOptions,
  defaultColumnDefinitionsFromSheetOptions,
  columnDefinitionsFromSheet,
  Column,
} from "@grit42/spreadsheet";
import { GritColumnDef, Table } from "@grit42/table";
import { useCallback, useEffect, useMemo, useState } from "react";
import styles from "./dataSheetStructureLoader.module.scss";
import { Form, FormField, FormFieldDef, useForm, useStore } from "@grit42/form";

const SHEET_OPTIONS_FORM_FIELDS: FormFieldDef[] = [
  {
    name: "ignore",
    display_name: "Skip this sheet",
    type: "boolean",
    default: false,
  },
  {
    name: "nameRowIndex",
    display_name: "Index of the row containing the column name",
    description: "name will be autogenerated if not specified",
    type: "integer",
    reference: "ignore",
    disabled: (ref) => ref,
  },
  {
    name: "identifierRowIndex",
    display_name: "Index of the row containing the column safe_name",
    description: "safe_name will be autogenerated if not specified",
    type: "integer",
    reference: "ignore",
    disabled: (ref) => ref,
  },
  {
    name: "descriptionRowIndex",
    display_name: "Index of the row containing the column description",
    type: "integer",
    reference: "ignore",
    disabled: (ref) => ref,
  },
  {
    name: "dataRowOffset",
    display_name: "Index of the first row containing data",
    type: "number",
    reference: "ignore",
    disabled: (ref) => ref,
  },
  {
    name: "columnOffset",
    display_name: "Index of the first column containing data",
    type: "string",
    reference: "ignore",
    disabled: (ref) => ref,
  },
];

const SheetOptionsForm = ({
  sheet,
  sheetOptions = defaultColumnDefinitionsFromSheetOptions,
  onChange,
}: {
  sheet: Sheet;
  sheetOptions: ColumnDefinitionsFromSheetOptions;
  onChange: any;
}) => {
  const form = useForm({
    defaultValues: sheetOptions,
  });

  const values = useStore(form.baseStore, ({ values }) => values);

  useEffect(() => {
    onChange((prev) => ({ ...prev, [sheet.id]: values }));
  }, [values, onChange, sheet.id]);

  return (
    <Surface>
      <Form<ColumnDefinitionsFromSheetOptions> form={form}>
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "1fr",
            gridAutoRows: "max-content",
            gap: "calc(var(--spacing) * 2)",
            paddingBottom: "calc(var(--spacing) * 2)",
          }}
        >
          {form.state.errorMap.onSubmit && (
            <div
              style={{
                gridColumnStart: 1,
                gridColumnEnd: -1,
                color: "var(--palette-error-main)",
              }}
            >
              {form.state.errorMap.onSubmit?.toString()}
            </div>
          )}
          {SHEET_OPTIONS_FORM_FIELDS.map((f) => (
            <FormField form={form} fieldDef={f} key={f.name} />
          ))}
        </div>
      </Form>
    </Surface>
  );
};

const SheetPreview = ({ sheet }: { sheet: Sheet }) => {
  const sampleData = useMemo(
    () => sampleSheetData(sheet).map((d, i) => ({ ...d, rowIndex: i + 1 })),
    [sheet],
  );
  const sampleDataColumns = useMemo(() => {
    const columns: GritColumnDef[] = [
      {
        id: "rowIndex",
        header: "",
        accessorKey: "rowIndex",
        size: 40,
        type: "integer",
      },
    ];
    for (let i = 0; i <= sheet.range.e.c; i++) {
      const alphaCol = utils.encode_col(i);
      columns.push({
        id: alphaCol,
        header: alphaCol,
        accessorKey: alphaCol,
      });
    }
    return columns;
  }, [sheet]);

  return (
    <Table
      columns={sampleDataColumns}
      data={sampleData}
      settings={{
        disableFilters: true,
        disableColumnReorder: true,
        disableColumnSorting: true,
        disableVisibilitySettings: true,
      }}
    />
  );
};

export interface SheetWithColumns extends Sheet {
  columns: Column[];
}

const SheetMapper = ({
  files,
  onSubmit,
}: {
  files: File[];
  onSubmit: (sheets: SheetWithColumns[]) => void;
}) => {
  const [selectedTab, setSelectedTab] = useState(0);
  const [sheetOptions, setSheetOptions] = useState<
    Record<string, ColumnDefinitionsFromSheetOptions>
  >({});
  const navigate = useNavigate();
  const {
    data: dataTypes,
    isLoading,
    isError,
    error,
  } = useEntityData("grit/core/data_types");

  const {
    data: structures,
    isLoading: isStructureLoading,
    isError: isStructureError,
    error: structureError,
  } = useQuery({
    queryKey: ["structures", files],
    queryFn: async () => {
      return await sheetDefinitionsFromFiles(files);
    },
    enabled: !!dataTypes,
  });

  const handleSubmit = useCallback(async () => {
    const sheetsWithColumns = await Promise.all(
      structures
        ?.filter((s) => sheetOptions[s.id]?.ignore === false)
        .map(async (s) => ({
          ...s,
          columns: await columnDefinitionsFromSheet(
            s,
            sheetOptions[s.id] ?? defaultColumnDefinitionsFromSheetOptions,
          ),
        })) ?? [],
    );

    onSubmit(sheetsWithColumns);
    navigate(`../edit/${sheetsWithColumns[0].id}`);
  }, [structures, onSubmit, navigate, sheetOptions]);

  if (!files?.length) {
    return <Navigate to="../files" />;
  }

  if (isLoading || isStructureLoading) {
    return <Spinner />;
  }

  if (isError || isStructureError) {
    return <ErrorPage error={error ?? structureError?.message} />;
  }

  return (
    <div
      style={{
        display: "grid",
        gridTemplateColumns: "1fr",
        gridTemplateRows: "min-content 1fr",
        height: "100%",
        width: "100%",
        overflow: "auto",
      }}
    >
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "baseline",
        }}
      >
        <h3 style={{ alignSelf: "baseline", marginBottom: "1em" }}>
          Data sheet definitions import: choose sheets to import and provide
          information about their structure
        </h3>

        <ButtonGroup>
          <Button onClick={() => navigate("..")}>Cancel</Button>
          <Button color="primary" onClick={handleSubmit}>
            Continue
          </Button>
        </ButtonGroup>
      </div>
      <Tabs
        selectedTab={selectedTab}
        onTabChange={setSelectedTab}
        className={styles.tab}
        tabs={
          structures?.map((s) => ({
            panelProps: {
              style: { overflow: "auto" },
            },
            key: s.name,
            name: s.name,
            panel: (
              <div
                style={{
                  overflow: "auto",
                  display: "grid",
                  gridTemplateColumns: "1fr max-content",
                  gridTemplateRows: "1fr",
                  gap: "var(--spacing)",
                  height: "100%"
                }}
              >
                <SheetPreview sheet={s} />
                <SheetOptionsForm
                  sheet={s}
                  sheetOptions={sheetOptions[s.id]}
                  onChange={setSheetOptions}
                />
              </div>
            ),
          })) ?? []
        }
      />
    </div>
  );
};

export default SheetMapper;
