services:
  db:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${GRIT42_PG_USER:-grit}
      - POSTGRES_DB=${GRIT42_PG_DB:-grit}-default
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-muchsecurepasswordwow}
    image: "grit42com/pgrdkit:16.3-2024.03.1"
    platform: linux/amd64
    restart: unless-stopped
    volumes:
      - ./postgres-data-prod:/var/lib/postgresql/data
  app:
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - SECRET_KEY_BASE=${SECRET_KEY_BASE:-muchsecurepasswordwow}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-muchsecurepasswordwow}
    image: "grit42com/grit-compounds:0.1.4"
    platform: linux/amd64
    restart: unless-stopped
