import { AnyFormApi, FormFields, useFormInput, useStore } from "@grit42/form";
import { CenteredSurface } from "@grit42/client-library/layouts";
import styles from "./spreadsheetProcessor.module.scss";

const SheetOptionsForm = ({
  sheetIndex,
  form,
}: {
  sheetIndex: number;
  form: AnyFormApi;
}) => {
  const included = useStore(
    form.store,
    ({ values }) =>
      !!values.sheets[sheetIndex]?.included as boolean | undefined,
  );

  const BooleanInput = useFormInput("boolean");
  const NumberInput = useFormInput("number");
  const StringInput = useFormInput("string");

  const Field = (form as any).Field;

  return (
    <CenteredSurface className={styles.sheetOptionsForm}>
      <FormFields columns={1}>
        <Field name={`sheets[${sheetIndex}].included`}>
          {(field: any) => (
            <BooleanInput
              className={styles.includeSwitch}
              disabled={false}
              error=""
              field={{
                name: `sheets[${sheetIndex}].included`,
                display_name: "Include this sheet",
                required: true,
                type: "boolean",
              }}
              handleChange={field.handleChange}
              handleBlur={field.handleBlur}
              value={field.state.value}
            />
          )}
        </Field>
        <Field
          name={`sheets[${sheetIndex}].headerRowIndex`}
          validators={{
            onChangeListenTo: [`sheets[${sheetIndex}].included`],
            onChange: ({ value, fieldApi }: any) => {
              if (
                !fieldApi.form.getFieldValue(`sheets[${sheetIndex}].included`)
              )
                return undefined;
              else if (value === null || value === undefined || value === "") {
                return `cannot be blank`;
              }
            },
          }}
        >
          {(field: any) => (
            <NumberInput
              disabled={!included}
              error={Array.from(new Set(field.state.meta.errors)).join("\n")}
              field={{
                name: `sheets[${sheetIndex}].headerRowIndex`,
                display_name: "Index of the row containing column identifiers",
                description: "name will be autogenerated if not specified",
                required: included,
                type: "integer",
              }}
              handleChange={field.handleChange}
              handleBlur={field.handleBlur}
              value={field.state.value}
            />
          )}
        </Field>
        <Field
          name={`sheets[${sheetIndex}].dataRowIndex`}
          validators={{
            onChangeListenTo: [`sheets[${sheetIndex}].included`],
            onChange: ({ value, fieldApi }: any) => {
              if (
                !fieldApi.form.getFieldValue(`sheets[${sheetIndex}].included`)
              )
                return undefined;
              else if (value === null || value === undefined || value === "") {
                return `cannot be blank`;
              }
            },
          }}
        >
          {(field: any) => (
            <NumberInput
              disabled={!included}
              error={Array.from(new Set(field.state.meta.errors)).join("\n")}
              field={{
                name: `sheets[${sheetIndex}].dataRowIndex`,
                display_name: "Index of the first row containing data",
                required: included,
                type: "integer",
              }}
              handleChange={field.handleChange}
              handleBlur={field.handleBlur}
              value={field.state.value}
            />
          )}
        </Field>
        <Field
          name={`sheets[${sheetIndex}].dataColumnOffset`}
          validators={{
            onChangeListenTo: [`sheets[${sheetIndex}].included`],
            onChange: ({ value, fieldApi }: any) => {
              if (
                !fieldApi.form.getFieldValue(`sheets[${sheetIndex}].included`)
              )
                return undefined;
              else if (value === null || value === undefined || value === "") {
                return `cannot be blank`;
              }
            },
          }}
        >
          {(field: any) => (
            <StringInput
              disabled={!included}
              error={Array.from(new Set(field.state.meta.errors)).join("\n")}
              field={{
                name: `sheets[${sheetIndex}].dataColumnOffset`,
                display_name: "Index of the first column containing data",
                required: included,
                type: "string",
              }}
              handleChange={field.handleChange}
              handleBlur={field.handleBlur}
              value={field.state.value}
            />
          )}
        </Field>
      </FormFields>
    </CenteredSurface>
  );
};

export default SheetOptionsForm;
